export const categories = ['Indoor Plants', 'Succulents', 'Tropical Plants'];

export const products = [
  {
    id: 'monstera-deliciosa',
    name: 'Monstera Deliciosa',
    category: 'Indoor Plants',
    price: 28,
    image: '/images/plants/monstera-deliciosa.svg',
    description: 'A leafy statement plant that enjoys a bright corner.',
  },
  {
    id: 'snake-plant',
    name: 'Snake Plant',
    category: 'Indoor Plants',
    price: 22,
    image: '/images/plants/snake-plant.svg',
    description: 'An easygoing upright plant for almost any room.',
  },
  {
    id: 'golden-pothos',
    name: 'Golden Pothos',
    category: 'Indoor Plants',
    price: 18.5,
    image: '/images/plants/golden-pothos.svg',
    description: 'A bright trailing vine with marbled green leaves.',
  },
  {
    id: 'fiddle-leaf-fig',
    name: 'Fiddle Leaf Fig',
    category: 'Indoor Plants',
    price: 42,
    image: '/images/plants/fiddle-leaf-fig.svg',
    description: 'Sculptural leaves bring a little height to your space.',
  },
  {
    id: 'peace-lily',
    name: 'Peace Lily',
    category: 'Indoor Plants',
    price: 24,
    image: '/images/plants/peace-lily.svg',
    description: 'Graceful deep-green foliage with a soft white bloom.',
  },
  {
    id: 'bird-of-paradise',
    name: 'Bird of Paradise',
    category: 'Indoor Plants',
    price: 48,
    image: '/images/plants/bird-of-paradise.svg',
    description: 'Broad tropical leaves make a bold, sunny accent.',
  },
  {
    id: 'echeveria',
    name: 'Echeveria',
    category: 'Succulents',
    price: 12,
    image: '/images/plants/echeveria.svg',
    description: 'A compact rosette that loves a bright windowsill.',
  },
  {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    category: 'Succulents',
    price: 16.5,
    image: '/images/plants/aloe-vera.svg',
    description: 'A sturdy, sun-loving succulent with fleshy leaves.',
  },
  {
    id: 'jade-plant',
    name: 'Jade Plant',
    category: 'Succulents',
    price: 15,
    image: '/images/plants/jade-plant.svg',
    description: 'Rounded leaves and a tidy shape make it a classic.',
  },
  {
    id: 'string-of-pearls',
    name: 'String of Pearls',
    category: 'Succulents',
    price: 19,
    image: '/images/plants/string-of-pearls.svg',
    description: 'Bead-like leaves spill neatly over a shelf or planter.',
  },
  {
    id: 'haworthia',
    name: 'Haworthia',
    category: 'Succulents',
    price: 13.5,
    image: '/images/plants/haworthia.svg',
    description: 'A small, striped rosette that is easy to place.',
  },
  {
    id: 'barrel-cactus',
    name: 'Golden Barrel Cactus',
    category: 'Succulents',
    price: 17,
    image: '/images/plants/barrel-cactus.svg',
    description: 'A rounded little cactus with a sunny, sculptural shape.',
  },
  {
    id: 'calathea-orbifolia',
    name: 'Calathea Orbifolia',
    category: 'Tropical Plants',
    price: 32,
    image: '/images/plants/calathea-orbifolia.svg',
    description: 'Silvery stripes add a soft pattern to broad leaves.',
  },
  {
    id: 'rubber-plant',
    name: 'Rubber Plant',
    category: 'Tropical Plants',
    price: 29.5,
    image: '/images/plants/rubber-plant.svg',
    description: 'Glossy, dark leaves give this plant a polished look.',
  },
  {
    id: 'areca-palm',
    name: 'Areca Palm',
    category: 'Tropical Plants',
    price: 38,
    image: '/images/plants/areca-palm.svg',
    description: 'Feathery fronds bring an airy, tropical feel indoors.',
  },
  {
    id: 'anthurium',
    name: 'Anthurium',
    category: 'Tropical Plants',
    price: 27,
    image: '/images/plants/anthurium.svg',
    description: 'A bright bloom sits above smooth, heart-shaped leaves.',
  },
  {
    id: 'boston-fern',
    name: 'Boston Fern',
    category: 'Tropical Plants',
    price: 23,
    image: '/images/plants/boston-fern.svg',
    description: 'Full, fine fronds add a fresh touch to a hanging pot.',
  },
  {
    id: 'philodendron-brasil',
    name: 'Philodendron Brasil',
    category: 'Tropical Plants',
    price: 21.5,
    image: '/images/plants/philodendron-brasil.svg',
    description: 'A low-fuss trailing plant with cheerful variegated leaves.',
  },
];
